# Generated by Django 4.0.5 on 2022-08-25 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bbox', models.JSONField()),
                ('coordinates', models.JSONField()),
                ('path', models.CharField(max_length=400)),
                ('time_from', models.DateField()),
                ('time_to', models.DateField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('mean_value', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
