# Generated by Django 4.0.5 on 2022-09-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthanalysis',
            name='area',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
