# Generated by Django 4.0.5 on 2022-08-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0002_healthanalysis_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthanalysis',
            name='path',
            field=models.FileField(default=None, upload_to='healthanalysis/'),
        ),
    ]
