# Generated by Django 4.0.5 on 2022-08-16 08:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0003_alter_healthanalysis_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthanalysis',
            name='path',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
