# Generated by Django 4.0.5 on 2022-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0004_alter_healthanalysis_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthanalysis',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='healthanalysis/'),
        ),
    ]
