# Generated by Django 4.0.5 on 2022-08-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0005_alter_healthanalysis_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthanalysis',
            name='path',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
