# Generated by Django 4.0.5 on 2022-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthanalysis', '0006_alter_healthanalysis_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthanalysis',
            name='max_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthanalysis',
            name='mean_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthanalysis',
            name='min_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
